//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZonasComune
    {
        public ZonasComune()
        {
            this.Elementos = new HashSet<Elemento>();
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int TipoZonaComunId { get; set; }
    
        public virtual ICollection<Elemento> Elementos { get; set; }
        public virtual ICollection<Reserva> Reservas { get; set; }
        public virtual TiposZonaComun TiposZonaComun { get; set; }
    }
}
